# -*- coding: utf-8 -*-
"""MRIScans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMaEPliy4wN-FdQkdmINzgNSNN_2lW7i
"""

from google.colab import drive
drive.mount('/content/drive')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("happyharrycn/uw-madison-gi-tract-image-segmentation-dataset")

print("Path to dataset files:", path)

import copy
import os
import random
import shutil
import zipfile
from math import atan2, cos, sin, sqrt, pi, log
import cv2
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.v2 as v2
import pandas as pd
from PIL import Image
from numpy import linalg as LA
from torch import optim, nn
from torch.utils.data import DataLoader, random_split
from torch.utils.data.dataset import Dataset
from torchvision import transforms
from tqdm import tqdm

!pip install solt
import solt as sl
import solt.transforms as slt

trfs = sl.Stream([
    slt.Rotate((-15, 15), padding='r'),
    slt.Shear(range_x=(-0.1, 0.1), range_y=(-0.1, 0.1), padding='r'),
    slt.Contrast(contrast_range=(0.6, 1.3)),
    slt.Brightness(brightness_range=(0.8, 1.2)),
    slt.Blur(p=0.1, blur_type='m', k_size=(3,)),
    slt.SaltAndPepper(p=0.1, gain_range=0.05),
    sl.SelectiveStream([
        sl.SelectiveStream([
            slt.CutOut(cutout_size=32),
            slt.CutOut(cutout_size=32),
            slt.CutOut(cutout_size=16),
            slt.CutOut(cutout_size=16),
            slt.CutOut(cutout_size=12),
            slt.CutOut(cutout_size=12),
            slt.CutOut(cutout_size=8),
            slt.CutOut(cutout_size=8),
        ], n=2),
        sl.Stream(),
    ], probs=[0.8, 0.2]),
])

!pip install wandb -qU
# Log in to your W&B account
import wandb
import random
import math

!wandb login --relogin

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv_op = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv_op(x)

class DownSample(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = DoubleConv(in_channels, out_channels)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

    def forward(self, x):
        down = self.conv(x)
        p = self.pool(down)

        return down, p

class UpSample(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.up = nn.ConvTranspose2d(in_channels, in_channels//2, kernel_size=2, stride=2)
        self.conv = DoubleConv(in_channels, out_channels)

    def forward(self, x1, x2):
        x1 = self.up(x1)

        # Fix spatial mismatch by padding x1 to match x2 size
        # This happens when input dimensions are not powers of 2 (like 266)
        diffY = x2.size()[2] - x1.size()[2]
        diffX = x2.size()[3] - x1.size()[3]

        x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2,
                        diffY // 2, diffY - diffY // 2])

        x = torch.cat([x1, x2], 1)
        return self.conv(x)

class UNet(nn.Module):
    def __init__(self, in_channels, num_classes):
        super().__init__()
        self.down_convolution_1 = DownSample(in_channels, 64)
        self.down_convolution_2 = DownSample(64, 128)
        self.down_convolution_3 = DownSample(128, 256)
        self.down_convolution_4 = DownSample(256, 512)

        self.bottle_neck = DoubleConv(512, 1024)

        self.up_convolution_1 = UpSample(1024, 512)
        self.up_convolution_2 = UpSample(512, 256)
        self.up_convolution_3 = UpSample(256, 128)
        self.up_convolution_4 = UpSample(128, 64)

        self.out = nn.Conv2d(in_channels=64, out_channels=num_classes, kernel_size=1)

    def forward(self, x):
        down_1, p1 = self.down_convolution_1(x)
        down_2, p2 = self.down_convolution_2(p1)
        down_3, p3 = self.down_convolution_3(p2)
        down_4, p4 = self.down_convolution_4(p3)

        b = self.bottle_neck(p4)

        up_1 = self.up_convolution_1(b, down_4)
        up_2 = self.up_convolution_2(up_1, down_3)
        up_3 = self.up_convolution_3(up_2, down_2)
        up_4 = self.up_convolution_4(up_3, down_1)

        out = self.out(up_4)
        return out

def pixel_decoder(encoded_pixels):
  encoded_pixels = encoded_pixels.split()
  starts = []
  lengths = []
  for i in range(0, len(encoded_pixels), 2):
    starts.append(int(encoded_pixels[i]))

  for i in range(1, len(encoded_pixels), 2):
    lengths.append(int(encoded_pixels[i]))

  mask = np.zeros(266 * 266, dtype=int)

  for i, start in enumerate(starts):
    start_idx = start - 1 # apparently RLE indexing starts at 1, so subtract to account for this
    end_idx = start_idx + lengths[i]
    mask[start_idx:end_idx] = 1

  return(mask, starts, lengths)

transform = v2.Compose([
    v2.ToImage(),
    v2.Resize((266, 266), antialias=True),
    v2.ToDtype(torch.float32, scale=False),
    # add normalization later
])

def apply_solt(solt_pipeline, img, mask):
    """Helper function to handle solt's dimension requirements cleanly."""
    # Force image to match mask dimensions to prevent DataContainer mismatch errors
    if img.shape[:2] != mask.shape[:2]:
        img = cv2.resize(img, (mask.shape[1], mask.shape[0]), interpolation=cv2.INTER_LINEAR)

    img_c = np.expand_dims(img, axis=-1) if img.ndim == 2 else img
    mask_c = np.expand_dims(mask, axis=-1) if mask.ndim == 2 else mask

    data = sl.core.DataContainer((img_c, mask_c), 'IM')
    res = solt_pipeline(data, return_torch=False)

    return res.data[0].squeeze(), res.data[1].squeeze()


class CustomDataset(Dataset):
  def __init__(self, slice_contour_pairs, transform=None, mask_data_cache=None, solt_transform=None):
    self.slice_contour_pairs = slice_contour_pairs
    self.transform = transform
    self.mask_data_cache = mask_data_cache # Store the cache
    self.solt_transform = solt_transform

  def __len__(self):
    return len(self.slice_contour_pairs)

  def __getitem__(self, idx):
    slice_id, slice_path, contour_csv_path = self.slice_contour_pairs[idx]
    img = cv2.imread(slice_path, cv2.IMREAD_UNCHANGED)

    # Convert to 8-bit uint8 to prevent OpenCV LUT crashes with solt
    if img is not None and img.dtype == np.uint16:
        img = (img / 256).astype(np.uint8)

    # Use the cached DataFrame
    df = self.mask_data_cache[contour_csv_path]
    slice_rows = df[df["SliceID"] == slice_id]

    # Initialize a single label map with zeros (background)
    label_map = np.zeros((266, 266), dtype=np.int64)

    for _, row in slice_rows.iterrows():
      encoded_pixels = row["EncodedPixels"]
      if str(encoded_pixels) != "-1":
        mask, _, _ = pixel_decoder(encoded_pixels)
        mask_2d = mask.reshape(266, 266)
        organ_id = int(row["MaskTypeID"]) + 1
        label_map[mask_2d == 1] = organ_id

    # Apply solt transforms using the clean helper function
    if self.solt_transform:
      img, label_map = apply_solt(self.solt_transform, img, label_map)

    if self.transform:
      img = self.transform(img)
    else:
      # If no torchvision transform, ensure img is a torch tensor with a channel dimension
      if isinstance(img, np.ndarray):
          img = torch.tensor(img, dtype=torch.float32).unsqueeze(0)

    target = torch.tensor(label_map, dtype=torch.long)
    return img, target

import random
slice_contour_pairs = []

os.listdir(path)
dataset_path = path + '/dataset'
dataset_cases = os.listdir(dataset_path)

for case_name in dataset_cases:
  case_path = dataset_path + "/" + case_name
  case_days = os.listdir(case_path)
  for case_day in case_days:
    scans_path = case_path + "/" + case_day + "/" + "scans"
    scans_list = os.listdir(scans_path)
    contours_path = case_path + "/" + case_day + "/" + "contours"
    contour_csv_path = contours_path + "/" + "masks_rle.csv"
    for scan in scans_list:
      slice_parts = scan.split("_")
      slice_id = slice_parts[0] + "_" + slice_parts[1]
      slice_path = scans_path + "/" + scan
      slice_contour_pairs.append((slice_id, slice_path, contour_csv_path))

unique_contour_csv_paths = set()
for _, _, contour_csv_path in slice_contour_pairs:
    unique_contour_csv_paths.add(contour_csv_path)

mask_dfs_cache = {}
for csv_path in unique_contour_csv_paths:
    mask_dfs_cache[csv_path] = pd.read_csv(csv_path)

# Group by scan_id to avoid data leakage, then do 70/10/20 split
unique_scan_ids = list(set([pair[1].split("/")[-3] for pair in slice_contour_pairs]))
random.seed(42) # Set seed for reproducibility
random.shuffle(unique_scan_ids)

num_scans = len(unique_scan_ids)
train_idx = int(0.7 * num_scans)
val_idx = train_idx + int(0.1 * num_scans)

train_scan_ids = set(unique_scan_ids[:train_idx])
val_scan_ids = set(unique_scan_ids[train_idx:val_idx])
test_scan_ids = set(unique_scan_ids[val_idx:])

train_pairs = []
val_pairs = []
test_pairs = []

for pair in slice_contour_pairs:
    scan_id = pair[1].split("/")[-3]
    if scan_id in train_scan_ids:
        train_pairs.append(pair)
    elif scan_id in val_scan_ids:
        val_pairs.append(pair)
    elif scan_id in test_scan_ids:
        test_pairs.append(pair)

print(f"Total train samples: {len(train_pairs)}")
print(f"Total validation samples: {len(val_pairs)}")
print(f"Total test samples: {len(test_pairs)}")

train_dataset = CustomDataset(train_pairs, transform, mask_data_cache=mask_dfs_cache, solt_transform=trfs)
val_dataset = CustomDataset(val_pairs, transform, mask_data_cache=mask_dfs_cache)
test_dataset = CustomDataset(test_pairs, transform, mask_data_cache=mask_dfs_cache)

class DiceLoss(nn.Module):
    def __init__(self, smooth=1):
        super(DiceLoss, self).__init__()
        self.smooth = smooth

    def forward(self, inputs, targets):
        inputs = F.softmax(inputs, dim=1)
        num_classes = inputs.shape[1]
        targets_one_hot = F.one_hot(targets.long(), num_classes=num_classes).permute(0, 3, 1, 2).float()

        inputs = inputs.reshape(inputs.shape[0], inputs.shape[1], -1)
        targets_one_hot = targets_one_hot.reshape(targets_one_hot.shape[0], targets_one_hot.shape[1], -1)

        intersection = (inputs * targets_one_hot).sum(2)
        dice = (2. * intersection + self.smooth) / (inputs.sum(2) + targets_one_hot.sum(2) + self.smooth)

        return 1 - dice.mean()

class CombinedLoss(nn.Module):
    def __init__(self):
        super(CombinedLoss, self).__init__()
        self.dice = DiceLoss()
        # Adding weights: Background (0) gets low weight, Organs (1-5) get high weight
        weights = torch.tensor([0.1, 1.0, 1.0, 1.0, 1.0, 1.0]).to(device)
        self.ce = nn.CrossEntropyLoss(weight=weights)

    def forward(self, inputs, targets):
        target_long = targets.long()
        return self.ce(inputs, target_long) + self.dice(inputs, target_long)

import torch
from torch.utils.data import DataLoader

device = "cuda" if torch.cuda.is_available() else "cpu"
learning_rate = 1e-4
batch_size = 8

train_dataloader = DataLoader(train_dataset, batch_size, num_workers=0, shuffle=True, pin_memory = True, persistent_workers=False, prefetch_factor=None)
val_dataloader = DataLoader(val_dataset, batch_size, num_workers=0, shuffle=False, pin_memory = True, persistent_workers=False, prefetch_factor=None)
test_dataloader = DataLoader(test_dataset, batch_size, num_workers=0, shuffle=False, pin_memory = True, persistent_workers=False, prefetch_factor=None)

# Updated num_classes to 6 (1 Background + 5 Organs) to match the indices 0-5
model = UNet(in_channels=1, num_classes=6).to(device)
optimizer = optim.AdamW(model.parameters(), lr=learning_rate)
criterion = CombinedLoss()

def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.train()
  train_loss = 0
  for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)
        # Target `y` is already (B, H, W), no need to squeeze(1)

        pred = model(X)
        loss = loss_fn(pred, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

        if batch % 100 == 0:
          loss_val, current = loss.item(), batch * len(X)
          print(f"loss: {loss_val:>7f}  [{current:>5d}/{size:>5d}]")
          # Log batch-level training loss
          wandb.log({"Train/Step_Loss": loss_val})

  avg_loss = train_loss / num_batches
  return avg_loss

def evaluate(dataloader, model, loss_fn, split_name="Validation"):
    num_batches = len(dataloader)
    model.eval()
    test_loss = 0
    total_correct_pixels = 0
    total_pixels = 0
    total_iou = 0

    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()

            # Calculate pixel-wise accuracy
            predicted_classes = pred.argmax(1)
            total_correct_pixels += (predicted_classes == y).sum().item()
            total_pixels += y.numel()

            # Simple Mean IoU calculation for the batch
            # (Ignores background class 0 for a more meaningful metric)
            for cls in range(1, 6):
                inter = ((predicted_classes == cls) & (y == cls)).sum().item()
                union = ((predicted_classes == cls) | (y == cls)).sum().item()
                if union > 0:
                    total_iou += inter / union

    avg_loss = test_loss / num_batches
    pixel_acc = total_correct_pixels / total_pixels
    avg_iou = total_iou / (num_batches * 5) # 5 organ classes

    print(f"{split_name} results:")
    print(f"  Avg loss: {avg_loss:>8f}")
    print(f"  Pixel Accuracy: {(100*pixel_acc):>0.2f}%")
    print(f"  Mean IoU (Organs): {avg_iou:>8f}\n")

    # Log epoch-level metrics to W&B with the split name as a prefix
    wandb.log({
        f"{split_name}/Epoch_Loss": avg_loss,
        f"{split_name}/Pixel_Accuracy": pixel_acc,
        f"{split_name}/Mean_IoU": avg_iou
    })

    return avg_loss

total_runs = 4
for run in range(total_runs):
  # 1️. Start a new run to track this script
  wandb.init(
      # Set the project where this run will be logged
      project="MRI Scans 5",
      # We pass a run name (otherwise it’ll be randomly assigned, like sunshine-lollypop-10)
      name=f"experiment_{run}",
      # Track hyperparameters and run metadata
      config={
      "learning_rate": 1e-4,
      "architecture": "Unet",
      "dataset": "GI Tract Image Segmentation",
      "epochs": 10,
      })

epochs = 10
train_loss_history = []
val_loss_history = []
best_val_loss = float('inf')

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")

    # 1. Train the model on the Training set
    train_loss = train(train_dataloader, model, criterion, optimizer)
    train_loss_history.append(train_loss)

    # Log epoch average training loss
    wandb.log({"Train/Epoch_Loss": train_loss, "epoch": t+1})

    # 2. Evaluate the model on the Validation set
    if len(val_dataloader) > 0:
        val_loss = evaluate(val_dataloader, model, criterion, split_name="Validation")
        val_loss_history.append(val_loss)

        # Save the model if validation loss improved
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_save_path = 'unet_june17_best_model.pth'
            torch.save(model.state_dict(), best_save_path)
            print(f"--> Validation loss improved to {best_val_loss:.6f}! Saved best model to {best_save_path}")
    else:
        print("Skipping val: val_dataloader is empty.")
print("Training Done!\n")

print("-------------------------------\nFinal Evaluation on Test Set:")
# 3. Only after ALL epochs are done, evaluate on the Test set
if len(test_dataloader) > 0:
    evaluate(test_dataloader, model, criterion, split_name="Test")

# Save the final model weights and log them to W&B
save_path = 'unet_june16_model_weights.pth'
torch.save(model.state_dict(), save_path)
print(f"Final model weights saved locally to {save_path}")
wandb.save(save_path)

# Log the best model to W&B as well if it was saved
if 'best_save_path' in locals():
    wandb.save(best_save_path)

print("Model weights logged to Weights & Biases.")

# Finish the W&B run
wandb.finish()

# Define the path where you want to save the model in your Google Drive
save_path = '/content/drive/MyDrive/unet_june16_model_weights.pth'

# Save the model's state dictionary (which contains the weights and biases)
torch.save(model.state_dict(), save_path)

print(f"Model weights saved successfully to {save_path}")

loaded_model = UNet(in_channels=1, num_classes=6).to(device)

loaded_model.load_state_dict(torch.load(save_path))

loaded_model.eval()
